In [1]:
import numpy as np
a = np.arange(10)
type(a)

numpy.ndarray

In [2]:
from numpy import *
a = arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a.dtype

dtype('int32')

In [4]:
a.shape

(10,)

In [7]:
m = array([arange(4), arange(4)])
m

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [8]:
m.shape

(2, 4)

In [11]:
a = array([arange(5,9), arange(4,8)])
a

array([[5, 6, 7, 8],
       [4, 5, 6, 7]])

In [12]:
a[1,2]

6

In [13]:
a = arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a[1:6]

array([1, 2, 3, 4, 5])

In [17]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [18]:
a[::2]

array([0, 2, 4, 6, 8])